#############################################################################
# Makefile for building: pathplan_gui
# Generated by qmake (2.01a) (Qt 4.8.4) on: ?? 12? 4 10:29:49 2014
# Project:  pathplan_gui.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile pathplan_gui.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		RMapViewer.cpp \
		RMap.cpp \
		RRangeScan.cpp \
		RPathPlan.cpp \
		RPathPlan_astar.cpp \
		RPathPlan_astarDyn.cpp moc_RMapViewer.cpp
OBJECTS       = main.o \
		RMapViewer.o \
		RMap.o \
		RRangeScan.o \
		RPathPlan.o \
		RPathPlan_astar.o \
		RPathPlan_astarDyn.o \
		moc_RMapViewer.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		pathplan_gui.pro
QMAKE_TARGET  = pathplan_gui
DESTDIR       = 
TARGET        = pathplan_gui

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: pathplan_gui.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile pathplan_gui.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile pathplan_gui.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/pathplan_gui1.0.0 || $(MKDIR) .tmp/pathplan_gui1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/pathplan_gui1.0.0/ && $(COPY_FILE) --parents RMapViewer.h RMap.h RRangeScan.h RPathPlan.h RPathPlan_astar.h RPathPlan_astarDyn.h .tmp/pathplan_gui1.0.0/ && $(COPY_FILE) --parents main.cpp RMapViewer.cpp RMap.cpp RRangeScan.cpp RPathPlan.cpp RPathPlan_astar.cpp RPathPlan_astarDyn.cpp .tmp/pathplan_gui1.0.0/ && (cd `dirname .tmp/pathplan_gui1.0.0` && $(TAR) pathplan_gui1.0.0.tar pathplan_gui1.0.0 && $(COMPRESS) pathplan_gui1.0.0.tar) && $(MOVE) `dirname .tmp/pathplan_gui1.0.0`/pathplan_gui1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/pathplan_gui1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

/usr/lib/x86_64-linux-gnu/qt4/bin/moc:
	(cd $(QTDIR)/src/tools/moc && $(MAKE))

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_RMapViewer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_RMapViewer.cpp
moc_RMapViewer.cpp: RMap.h \
		RPathPlan.h \
		RRangeScan.h \
		RMapViewer.h \
		/usr/lib/x86_64-linux-gnu/qt4/bin/moc
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) RMapViewer.h -o moc_RMapViewer.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp RMapViewer.h \
		RMap.h \
		RPathPlan.h \
		RRangeScan.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

RMapViewer.o: RMapViewer.cpp RMap.h \
		RMapViewer.h \
		RPathPlan.h \
		RRangeScan.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RMapViewer.o RMapViewer.cpp

RMap.o: RMap.cpp RMap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RMap.o RMap.cpp

RRangeScan.o: RRangeScan.cpp RRangeScan.h \
		RMap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RRangeScan.o RRangeScan.cpp

RPathPlan.o: RPathPlan.cpp RPathPlan.h \
		RMap.h \
		RPathPlan_astar.h \
		RRangeScan.h \
		RPathPlan_astarDyn.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RPathPlan.o RPathPlan.cpp

RPathPlan_astar.o: RPathPlan_astar.cpp RPathPlan_astar.h \
		RPathPlan.h \
		RMap.h \
		RRangeScan.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RPathPlan_astar.o RPathPlan_astar.cpp

RPathPlan_astarDyn.o: RPathPlan_astarDyn.cpp RPathPlan_astar.h \
		RPathPlan.h \
		RMap.h \
		RRangeScan.h \
		RPathPlan_astarDyn.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RPathPlan_astarDyn.o RPathPlan_astarDyn.cpp

moc_RMapViewer.o: moc_RMapViewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_RMapViewer.o moc_RMapViewer.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

